// Code Generated by Sidekick is for learning and experimentation purposes only.
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { WomenComponent } from './women'; // <-- use the correct class name

describe('WomenComponent', () => {
  let component: WomenComponent;
  let fixture: ComponentFixture<WomenComponent>;

  beforeEach(async () => {
    await TestBed.configureTestingModule({
      imports: [WomenComponent]
    }).compileComponents();

    fixture = TestBed.createComponent(WomenComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  it('should create', () => {
    expect(component).toBeTruthy();
  });
});
